# Chain Multiple Tasks with Continuations

`Task.ContinueWith()` method is used to make chains of multiple tasks. Each next task in a chain will not be scheduled for execution until the current task has completed successfully, faulted due to an unhandled exception, or exited out early due to being canceled.

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        Task tsk1 = Task.Run(() =>
        {
            Thread.Sleep(100);
            Console.WriteLine("tsk1");
        });

        //Run tsk2 as soon tsk1 get completed
        Task tsk2 = tsk1.ContinueWith((t) =>
        {
            Thread.Sleep(500);
            Console.WriteLine("tsk2");
        });

        tsk2.Wait();
    }
}
// tsk1
// tsk2
```

## `Task<TResult>` with Continuation

`tsk1.ContinueWith()` executes and returns a new task when has completed its execution. Here `"t"` is the reference of `tsk1` and can be useable in the body of a lambda expression:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        Task<string> tsk1 = Task.Run(() =>
        {
            Thread.Sleep(100);
            return "Ali";
        });

        //Run tsk2 as soon tsk1 get completed
        Task tsk2 = tsk1.ContinueWith((t) =>
        {
            //Wait for tsk1 and return its value
            string name = t.Result;
            Console.WriteLine("My Name is: {0}", name);
        });

        tsk2.Wait();
    }
}
// Output:
// My Name is: Ali
```

## `TaskContinuationOption()`

`TaskContinuationOption()` is an enumeration that is used to specify when a task in a continuewith chain gets executed. The following are some of the most commong enums for **TaskContinuationOption**:

* **OnlyOnFaulted** Specifies that the continuation task should be scheduled only if its  antecedent threw an unhandled exception.
* **NotOnFaulted** Specifies that the continuation task should be scheduled if its antecedent doesn't throw an unhandled exception.
* **OnlyOnCanceled** Specifies that the continuation should be scheduled only if its antecedent was canceled. A task is canceled if its Task.Status property upon completion is `TaskStatus.Canceled`.
* **NotOnCanceled** Specifies that the continuation task should be scheduled if its antecedent was not canceled.
* **OnlyOnRanToCompletion** Specifies that the continuation task should be scheduled if its antecedent ran to completion.
* **NotOnRanToCompletion** Specifies that the continuation task should be scheduled if its antecedent doesn't run to completion.

Example:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        Task<string> tsk1 = Task.Run(() =>
        {
            throw new Exception();
            Console.WriteLine("tsk1 ran");
            Thread.Sleep(100);
            return "Ali";
        });

        Task tsk2 = tsk1.ContinueWith((t) =>
        {
            Console.WriteLine("tsk2 ran when tsk1 threw an exception");
        }, TaskContinuationOptions.OnlyOnFaulted);

        tsk2.Wait();
    }
}
// Output:
// tsk2 ran when tsk1 threws an exception
```

## `Task.FromResult<T>`

This method creates a `Task<TResult>` object whose `Task<TResult>.Result` property is result and whose Status property is `RanToCompletion`. The method is commonly used when the return value of a task is immediately known without executing a longer code path.

There are two common use cases:

1. When you're implementing an interface that allows **asynchronous** callers, but your implementation is **synchronous**.
1. When you're stubbing/mocking asynchronous code for **testing**.